# general settings
name: CodeFormer_stage4
model_type: CodeFormerJointRefModel
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: FFHQ-Ref
    type: FFHQRefJointDataset
    dataroot_gt: D:\idpfvsr/datasets\FFHQ-Ref\downsampled_x2\train\hq  # FFHQ
    filename_tmpl: '{}'
    io_backend:
      type: disk

    in_size: 512
    gt_size: 512
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    use_hflip: false  # Do not use hflip at this stage, because it might affect identity (faces are not symmetric)
    use_corrupt: true

    blur_kernel_size: 41
    use_motion_kernel: false
    motion_kernel_prob: 0.001
    kernel_list: ['iso', 'aniso']
    kernel_prob: [0.5, 0.5]
    # small degradation in stageIII
    blur_sigma: [0.1, 10]
    downsample_range: [1, 12]
    noise_range: [0, 15]
    jpeg_range: [60, 100]
    # large degradation in stageII
    blur_sigma_large: [1, 15]
    downsample_range_large: [4, 30]
    noise_range_large: [0, 20]
    jpeg_range_large: [30, 80]

    # latent_gt_path: ~ # without pre-calculated latent code
    latent_gt_path: weights/latent_gt_code1024.pth # without pre-calculated latent code

    # Reference related settings
    conditional: true
    load_reference: true
    num_references: 1
    ref_conds_path: ~
    id_embeddings_path: D:/idpfvsr/datasets/FFHQ/no_ref/downscaled_x2/FFHQ_id_embeddings_512_arcface50.pt
    component_path: ~

    # data loader
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: FFHQ-Ref-Val-Severe
    type: PairedImageRefDataset  # TODO: validation dataset
    dataroot_lq: D:\idpfvsr/datasets\FFHQ-Ref\downsampled_x2\val\lq\severe
    dataroot_gt: D:\idpfvsr/datasets\FFHQ-Ref\downsampled_x2\val\hq
    io_backend:
      type: disk
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    scale: 1
    conditional: true
    load_reference: true
    num_references: -1

  # val:
  #   name: CelebA-Test
  #   type: PairedImageRefDataset  # TODO: validation dataset
  #   dataroot_lq: D:\idpfvsr\datasets\CelebA-Test-Ref\celeba_test_split\test\lq
  #   dataroot_gt: D:\idpfvsr\datasets\CelebA-Test-Ref\celeba_test_split\test\hq
  #   io_backend:
  #     type: disk
  #   mean: [0.5, 0.5, 0.5]
  #   std: [0.5, 0.5, 0.5]
  #   scale: 1
  #   conditional: true
  #   load_reference: true
  #   num_references: -1
    
# network structures
network_g:
  type: IdpCodeFormerV1
  dim_embd: 512
  n_head: 8
  n_layers: 9
  codebook_size: 1024
  connect_list: ['32', '64', '128', '256']
  fix_modules: ['quantize','generator']

network_vqgan: # this config is needed if no pre-calculated latent
  type: VQAutoEncoder
  img_size: 512
  nf: 64
  ch_mult: [1, 2, 2, 4, 4, 8]
  quantizer: 'nearest'
  codebook_size: 1024

network_d:
  type: VQGANDiscriminator
  nc: 3
  ndf: 64
  n_layers: 4

# path
path:
  pretrain_network_g: 'weights/CodeFormer/codeformer.pth' # pretrained G model in StageII 
  # pretrain_network_g: 'experiments/CodeFormer_stage4_second/models/net_g_65000.pth' # pretrained G model in StageII 
  param_key_g: params_ema
  strict_load_g: false
  pretrain_network_d: 'weights/CodeFormer/vqgan_discriminator.pth' # pretrained D model in StageII
  resume_state: ~

# base_lr(4.5e-6)*bach_size(4)
train:
  use_hq_feat_loss: true
  feat_loss_weight: 1.0
  cross_entropy_loss: true
  entropy_loss_weight: 0.5
  scale_adaptive_gan_weight: 0.1  # someone said 0.6 is better

  optim_g:
    type: Adam
    lr: !!float 1e-5
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [150000]
    restart_weights: [1]
    eta_min: !!float 2e-5

  total_iter: 150000

  warmup_iter: -1  # no warm up
  ema_decay: 0.997

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: LPIPSLoss
    loss_weight: 1.0
    use_input_norm: true
    range_norm: true

  gan_opt:
    type: GANLoss
    gan_type: hinge
    loss_weight: !!float 1.0 # adaptive_weighting

  # TODO: implement the ID loss and see how it works
  # id_opt:
  #   type: Cosine
  #   loss_weight: 1.0
  #   loss_weight: !!float 1.0

  use_adaptive_weight: true

  net_g_start_iter: 0
  net_d_iters: 1
  net_d_start_iter: 5001
  manual_seed: 0

# validation settings
val:
  # val_freq: !!float 5e10 # no validation
  # val_freq: !!float 5000 
  val_freq: !!float 1e4
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29413

find_unused_parameters: true
